#ifndef __OUTPUT_H_INCLUDED__
#define __OUTPUT_H_INCLUDED__

#include "Proxy.h"

class Output : public Proxy
{
public:
	using Proxy::Proxy;

	enum subpixel {
		WL_OUTPUT_SUBPIXEL_UNKNOWN = 0, 
		WL_OUTPUT_SUBPIXEL_NONE = 1, 
		WL_OUTPUT_SUBPIXEL_HORIZONTAL_RGB = 2, 
		WL_OUTPUT_SUBPIXEL_HORIZONTAL_BGR = 3, 
		WL_OUTPUT_SUBPIXEL_VERTICAL_RGB = 4, 
		WL_OUTPUT_SUBPIXEL_VERTICAL_BGR = 5
	};
	enum transform {
		WL_OUTPUT_TRANSFORM_NORMAL = 0, 
		WL_OUTPUT_TRANSFORM_90 = 1, 
		WL_OUTPUT_TRANSFORM_180 = 2, 
		WL_OUTPUT_TRANSFORM_270 = 3, 
		WL_OUTPUT_TRANSFORM_FLIPPED = 4, 
		WL_OUTPUT_TRANSFORM_FLIPPED_90 = 5, 
		WL_OUTPUT_TRANSFORM_FLIPPED_180 = 6, 
		WL_OUTPUT_TRANSFORM_FLIPPED_270 = 7
	};
	enum mode {
		WL_OUTPUT_MODE_CURRENT = 0x1, 
		WL_OUTPUT_MODE_PREFERRED = 0x2
	};
};

#endif
